version: '3'
services:
  db:
    image: mysql:8.0
    ports:
      - 3360:3360
    volumes:
      - mini-project-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mini_golang_project_v2
  
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - mini-project-redis-data:/var/lib/redis

  app:
    image: vietthangc1/mini_golang_project
    build: .
    restart: always
    ports:
      - 3000:3000
    working_dir: /app
    depends_on:
      - db
    environment:
      REDISHOST: redis
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: mini_golang_project_v2
      MYSQL_DB_TEST: mini_golang_project_v2_test
      MIGRATE_DIR: migrations/mysql
      TOKEN_HOUR_LIFESPAN: 1
      API_SECRET: youaremydestiny
      PORT: :3000

volumes:
  mini-project-mysql-data:
    driver: local
  mini-project-redis-data:
    driver: local