// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/vietthangc1/mini-web-golang/app"
	"github.com/vietthangc1/mini-web-golang/handlers"
	"github.com/vietthangc1/mini-web-golang/models"
	"github.com/vietthangc1/mini-web-golang/modules"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func InitializeApp() (app.App, error) {
	db, err := models.ConnectDatabaseORM()
	if err != nil {
		return app.App{}, err
	}
	productRepository := modules.NewProductRepository(db)
	userRepository := modules.NewUserRepository(db)
	cacheProducts := app.NewCacheInstance()
	handler := handlers.NewHandler(productRepository, userRepository, cacheProducts)
	engine := app.NewRouter(handler)
	appApp := app.NewApp(engine, handler)
	return appApp, nil
}
